from __future__ import annotations

PENDING_STATUS = "待处理"
PROCESSING_STATUS = "处理中"
COMPLETED_STATUS = "已完成"
FAILED_STATUS = "失败"

DEFAULT_VIDEO_TYPE = "其他"
DEFAULT_ESTIMATED_TIME = "2-5分钟"

PENDING_LIKE_STATUSES = {PENDING_STATUS, PROCESSING_STATUS}

